@host=https://localhost:7038

POST {{host}}/Breakfast/create
Content-Type: application/json

{
    "name":"Vegan Sunshine",
    "description":"Vegan Everything! Join Us Now Eat Your Best Breakfast .",
    "startDateTime":"2022-04-08T08:00:00",
    "endDateTime":"2022-04-08T11:00:00",
    "savory":[
        "Oatmeal",
        "Omelette",
        "Avocado Toast",
        "Salad"
    ],
    "sweet":[
        "Cookie"
    ]
}